export const FETCH_MEASURES_REQUEST = 'FETCH_MEASURES_REQUEST';
export const FETCH_MEASURES_SUCCESS = 'FETCH_MEASURES_SUCCESS';
export const FETCH_MEASURES_FAILURE = 'FETCH_MEASURES_FAILURE';

export const FETCH_BEHAVIORS_REQUEST = 'FETCH_BEHAVIORS_REQUEST';
export const FETCH_BEHAVIORS_SUCCESS = 'FETCH_BEHAVIORS_SUCCESS';
export const FETCH_BEHAVIORS_FAILURE = 'FETCH_BEHAVIORS_FAILURE';

export const FETCH_TRANSGRESSIONS_REQUEST = 'FETCH_TRANSGRESSIONS_REQUEST';
export const FETCH_TRANSGRESSIONS_SUCCESS = 'FETCH_TRANSGRESSIONS_SUCCESS';
export const FETCH_TRANSGRESSIONS_FAILURE = 'FETCH_TRANSGRESSIONS_FAILURE';
