export const ADD_OCCURRENCE_REQUEST = 'ADD_OCCURRENCE_REQUEST';
export const ADD_OCCURRENCE_SUCCESS = 'ADD_OCCURRENCE_SUCCESS';
export const ADD_OCCURRENCE_FAILURE = 'ADD_OCCURRENCE_FAILURE';

export const DELETE_OCCURRENCE_REQUEST = 'DELETE_OCCURRENCE_REQUEST;';
export const DELETE_OCCURRENCE_SUCCESS = 'DELETE_OCCURRENCE_SUCCESS;';
export const DELETE_OCCURRENCE_FAILURE = 'DELETE_OCCURRENCE_FAILURE;';
