export const COUNT_STUDENT_REQUEST = 'COUNT_STUDENT_REQUEST';
export const COUNT_STUDENT_SUCCESS = 'COUNT_STUDENT_SUCCESS';
export const COUNT_STUDENT_FAILURE = 'COUNT_STUDENT_FAILURE';

export const RESUME_OCCURRENCES_REQUEST = 'RESUME_OCCURRENCES_REQUEST';
export const RESUME_OCCURRENCES_SUCCESS = 'RESUME_OCCURRENCES_SUCCESS';
export const RESUME_OCCURRENCES_FAILURE = 'RESUME_OCCURRENCES_FAILURE';

export const RESUME_BEHAVIOR_REQUEST = 'RESUME_BEHAVIOR_REQUEST';
export const RESUME_BEHAVIOR_SUCCESS = 'RESUME_BEHAVIOR_SUCCESS';
export const RESUME_BEHAVIOR_FAILURE = 'RESUME_BEHAVIOR_FAILURE';
